# Generated by Django 6.0.2 on 2026-02-24 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('alignment', models.CharField(choices=[('ORDER', 'Order'), ('CHAOS', 'Chaos'), ('NEUTRAL', 'Neutral'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('location_type', models.CharField(choices=[('PLANET', 'Planet'), ('CITY', 'City'), ('STATION', 'Station'), ('REGION', 'Region'), ('ORBIT', 'Orbit'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('controlling_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_locations', to='universe.faction')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='universe.universe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='faction',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='universe.universe'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('era', models.IntegerField(choices=[(0, 'BI (Before Impact)'), (1, 'PI (Post Impact)')], default=1)),
                ('year', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('event_type', models.CharField(choices=[('CATASTROPHE', 'Catastrophe'), ('DIPLOMACY', 'Diplomacy'), ('POLITICAL', 'Political'), ('SOCIAL', 'Social'), ('SCIENTIFIC', 'Scientific'), ('MILITARY', 'Military'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_major', models.BooleanField(default=False)),
                ('factions', models.ManyToManyField(blank=True, related_name='events', to='universe.faction')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='universe.location')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='universe.universe')),
            ],
            options={
                'ordering': ['era', 'year', 'day', 'created_at'],
            },
        ),
    ]
