# Generated by Django 6.0.2 on 2026-02-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
